service: aws-lambda-mailing-service

frameworkVersion: '^4.0.0'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    RESEND_API_KEY: ${env:RESEND_API_KEY}
    RESEND_AUDIENCE_ID: ${env:RESEND_AUDIENCE_ID}

functions:
  joinWaitList:
    handler: dist/handler.handler
    events:
      - http:
          path: contacts
          method: post

package:
  individually: true
  exclude:
    - node_modules/**
  include:
    - dist/**
    - node_modules/**

plugins:
  - serverless-offline