service: mailing-service

frameworkVersion: '^4.0.0'

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3
  environment:
    RESEND_API_KEY: ${env:RESEND_API_KEY}
    RESEND_AUDIENCE_ID: ${env:RESEND_AUDIENCE_ID}

functions:
  addContact:
    handler: dist/handler.handler
    events:
      - http:
          path: contacts
          method: post
          cors:
            origin: 'https://tripilog.com'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

package:
  individually: true
  excludeDevDependencies: true
  include:
    - dist/**
    - node_modules/**

plugins:
  - serverless-offline